name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: scan image with Aqua
  	  env:
        AQUA_REG_USER: ${{ secrets.AQUA_REG_USER }}
        AQUA_REG_PW: ${{ secrets.AQUA_REG_PW }}
        SCANNER_TOKEN: ${{ secrets.SCANNER_TOKEN }}
      run: |
      docker login registry.aquasec.com -u ${{ secrets.AQUA_REG_USER }} -p ${{ secrets.AQUA_REG_PW }}
	    docker run -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:latest-saas scan -H https://3772126de8.cloud.aquasec.com/ -A ${{ secrets.SCANNER_TOKEN }} --local my-demo-image:${{ github.sha }} --socket docker

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} quay.io/mmurhamm:${{ github.sha }}

    - name: Push to Registry
#	  env:
#	    QUAY_USER: ${{ secrets.QUAY_USER }}
#	    QUAY_PW: ${{ secrets.QUAY_PW }}
      run: echo "docker push quay.io/mmurhamm:${{ github.sha }}"
#         |
#	    docker login registry.aquasec.com -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PW }}
#       docker push quay.io/mmurhamm:${{ github.sha }}
